#!/usr/bin/env python3
"""fmo.py -- FRONT MISSION ONLINE world responder (TCP 61300).

FMO's world port was measured 2026-08-17 (pol-shim's connect() hook; the port is
also the single occurrence of the immediate 61300 in the whole unpacked image, at
0x611760e7). The host is region-selected from a table in the DLL:
`W20_`->fmo01, `DWJ_`->fmo02, `W2U_`->fmo03, `DWU_`->fmo04. A US Viewer is W20,
so this answers `fmo01.pol.com:61300`.

Everything below is read out of the unpacked client DLL (FrontMissionOnline.dll
dumped from memory by the shim's poldump tool, ImageBase 0x61000000) and
verified against live captures.

THE PACKET -- from the initializer at 0x61199fc0, which zero-fills then writes
each field, so the boundaries are the compiler's, not a guess:

    +0x00  u16  total length = payload + 0x14   (the send-arm sends word[+0x00])
    +0x02  u16  flags -- the meaningful half is BYTE +0x03, see below
    +0x04  u16  checksum      (seeded 0xFE60 before it is computed)
    +0x06  u16  MESSAGE id    -- this is the message identity
    +0x08  u16  connection id -- 0 until the server assigns one
    +0x0A       zero
    +0x10  u32  packet sequence -- rolls 0x1000..0x1FFF, restarts per session
    +0x14       payload

WARNING: `+0x10` IS A REQUEST/REPLY CORRELATION ID. A REPLY MUST ECHO THE REQUEST'S.
The poll every waiting state uses, 0x61199E30, ends with:

    eax = ctx[0x7580]        ; the rx buffer
    edx = [eax+0x10]         ; the received packet's +0x10
    cmp edx, [esp+4]         ; against the HANDLE the caller is waiting on
    jne -> return 0          ; NOT MY REPLY -- discarded, and the state stays put

and that handle is the sequence the CLIENT stamped on its own outbound request.
So a reply carrying our own counter is silently dropped: no error, no
disconnect, the state machine simply never advances.

WARNING: This cost hours and hid behind a coincidence. Our counter and the client's
both start at 0x1001 and both increment per packet, so our 0x0322 reply happened
to carry 0x1002 exactly when the client was waiting on 0x1002 -- it was accepted
for the wrong reason. Message 1 then carried 0x1003, matched nothing, and the
login parked in state 2 for ever. Two independent counters agreeing by accident
is worse than no match at all, because it makes the mechanism look understood.

WARNING: `+0x10` is also NOT AN OPCODE. 0x61199d40 does inc / and 0xfff /
or 0x1000 and stores it there. The first two packets of a session are always
0x1001 and 0x1002, which is exactly what makes them look like opcodes. Message
identity is `+0x06`.

BYTE +0x03 IS A FLAGS BYTE -- from the receive path at 0x61199c0b..0x61199c37:
    bit 0   the body is ENCRYPTED: `len-4` bytes from +0x04 go through the
            crypto context at ctx+0x7606 (RX) / ctx+0x780A (TX), reset by
            0x611a3ba0. The send side sets it (`or byte [eax+3],1`) only once
            ctx+0x7602 is non-zero, i.e. after a session key exists.
    bit 1   a checksum is present and must verify.
Decrypt happens BEFORE the checksum check. Every packet seen so far is 0x02:
checksummed, not encrypted.

THE CHECKSUM -- the client's own validator is at 0x61199c34, so this is its
algorithm rather than a fit to samples:

    mov bx, word [eax+4]      ; keep the received value
    mov word [eax+4], dx      ; zero ONLY the u16 at +0x04
    loop over `length` bytes from +0x00, accumulating into dx
    cmp bx, dx                ; 16-bit compare; mismatch -> ctx+0x75be = -14043

    => chk = sum(all packet bytes, with ONLY +0x04..+0x05 zeroed) & 0xFFFF

WARNING: Read `+0x04` as a u32 and you will zero four bytes to compute it, wiping
`+0x06` -- which is inside the sum. Every candidate then comes out short by
exactly bytesum(+0x06), and that shortfall masquerades as a per-message-type
constant. That cost a whole sweep. A checksum that fits `sum + K` with K varying
by message type means A HEADER FIELD IS MISSING FROM YOUR SUM.

WHAT THE CLIENT SENDS, AND WHAT WE ANSWER

    0x0065  version.     payload = u32 0, then the region+patch version string
                         in a 36-byte field ("W20_20260813_1" -- ours, from
                         the W20-0004 patch mirror's latest_version, where SE's
                         would read 2005/2006).
    0x0321  credentials. 80-byte payload on the PC, 52 on the PS2 (the console
                         sends the polcore blob alone -- see CRED_LEN_PS2).
                         DECODED -- see below; the high-entropy part is
                         polcore's, not FMO's, so no cipher had to fall.

The credentials payload is laid out by the sender at 0x61179bfa, which is also
what confirms the initializer's signature `init(msg, payload_size, conn_id)`:

    push 0 / push 0x50 / push 0x321 / call 0x61199fc0   -> payload pointer
    call [polcore+0xEA0]; mov ecx,0xd; rep movsd        -> 13 dwords = 52 bytes
    mov edx,[ebp+0x1a4]; mov [ebx+0x34],edx             -> the REGION enum
    16 bytes from [ebp+0x7654] (near a [polcore+0xFAC] call) -> [ebx+0x38]

    +0x00  52B  polcore-minted auth blob. Opaque to FMO -- it copies it whole.
    +0x34  u32  REGION id: 0x0A W20, 0x0B DWJ, 0x0C W2U, 0x0D DWU. The same
                enum the config block at 0x611760xx uses to pick fmo01..fmo04.
                It is NOT a length, which is what 0a 00 00 00 looks like.
    +0x38  16B  polcore identity, STABLE ACROSS SESSIONS for one install.
    +0x48   8B  zero.

Measured across two live sessions: everything above +0x34 is byte-identical, the
52-byte blob varies per session. That is the shape you would expect of a session
token plus a fixed machine/account identity -- and it means the interesting half
belongs to polcore, whose auth our own server already mints elsewhere.

The client pipelines both without waiting for a reply.

    MESSAGE 2 IS THE HANDSHAKE ANSWER. At 0x61199c79, once a packet validates:
        mov [esi+0x28], 4          ; state := 4
        cmp word [eax+6], 2        ; message id == 2 ?
        mov cx, word [eax+8]       ; then latch the packet's +0x08 ...
        mov word [esi+0x75bc], cx  ; ... as the connection id
    So a reply carrying `+0x06 = 2` hands the client a connection id at +0x08,
    which its own initializer then writes into every later packet's +0x08.

WARNING: **SESSION ENCRYPTION IS ARMED LATER IN THE LOGIN, AND THE KEY IS POLCORE'S.**
`0x61199eb0` takes a **20-byte** key and does:

    init crypto ctx [esi+0x7606] (key, 0x14, 1)    ; RX
    init crypto ctx [esi+0x780A] (key, 0x14, 1)    ; TX
    mov dword [esi+0x7602], 1                      ; the switch

`ctx+0x7602` is exactly what the send-arm tests before setting `+0x03` bit 0, so
from that call on, EVERY packet is enciphered both ways.

VERIFIED: **AND WE HAVE THE KEY.** It is 20 bytes: 16 from `[polcore+0xFAC]` and 4 from
OUR `0x0322` reply (packet `+0x1C` -> `ctx+0x7650`). Tapped live 2026-08-17 with
pol-shim's `[fmokey]`, polcore's 16 are **ALL ZERO** -- our auth stack never
populates its session-key field, which is the same fact as the PC crypto RE's "login
works end to end with K=0". So the server knows the whole key and no shim needs
to stay resident.

WARNING: **That is a property of OUR login, not of FMO.** Against real Square Enix those
16 bytes would presumably not be zero. Do not restate this as "FMO uses a zero
key".

THE CIPHER IS PLAIN RC4 -- `0x611a3bb0` is a textbook KSA and `0x611a3c60` a
textbook PRGA. See the RC4 class below for the context layout and the mode byte.

WHAT IS STILL UNKNOWN -- do not let this file imply otherwise:
  * the payload the client wants alongside message 2 (empty is what we try);
  * the command layer. Later packets carry commands validated at 0x61070670 as
    {u32 Size; u32 CommandID}, Size < 0x800 and a multiple of 4, CommandID
    < 0x130. The handshake packets do NOT have that shape.
  * the credential cipher, so nobody is authenticated here. (The 52-byte blob is
    polcore's; the SESSION cipher below is a separate thing and is solved.)
  * the UDP world channel. FMO imports sendto/recvfrom and no connect/send/recv,
    and a SOCK_DGRAM socket is created live right before the TCP dial. This file
    serves the TCP door ONLY. The sender is 0x611E23B4 -> 0x611FED70, and it
    takes the SAME 20-byte endpoint struct as everything else, out of an object
    field (+0x10E8) rather than out of a packet we have decoded.
  * WHICH VALUES the game-phase structures may carry. 2026-08-18 decoded their
    LAYOUT -- see the 0x0150 and 0x0154 notes, where every field carries the
    address it was read at -- but the map, script, music and unit id spaces live
    in the data containers (data/??/F??/D??.DAT), which are not decoded. The one
    exception is MapKind, whose legal bands are compares in the client itself.
    Everything this file sends for those fields is a PROBE and is logged as one.
  * the 88-byte structure that both 0x0153 (-> globals+0xD0) and every 0x0155
    LoginGroup entry (-> globals+0x128) carry. Same size, adjacent slots, no
    identified reader in either case.

    python fmo.py --selftest      # no socket, no client

STATIC RE. Every address in this file is a virtual address in the unpacked client
DLL (FrontMissionOnline.dll, ImageBase 0x61000000) and can be followed in any
disassembler that loads the image at that base.
"""

# The code lives in the fmoserver package, one module per concern
# (fmoserver/__init__.py lists them). This file is the entry point the
# container runs (`python fmo.py`) and a compatibility facade:
# `import fmo` still resolves every top-level name of the old single file,
# reading or writing, to the module that owns it, so tools and tests written
# against the flat file keep working.
import argparse
import importlib
import sys
import types

# ONE COPY OF THIS MODULE. The container runs `python fmo.py`, so the
# running copy is `__main__`, and a later `import fmo` (the package's own
# deps.flat_globals, a tool) would otherwise load a second copy.
if __name__ == "__main__":
    sys.modules.setdefault("fmo", sys.modules[__name__])

# Which fmoserver module owns each name that `fmo.<name>` reaches. A new
# top-level name that a tool or test reads or patches through fmo gets a line.
_OWNERS = {
    'A2_KINDS': 'cosmetics',
    'A2_PILOT': 'cosmetics',
    'A2_WANZER': 'cosmetics',
    'A3_COUNT_OFF': 'cosmetics',
    'A3_ROW_LEN': 'cosmetics',
    'A3_ROW_MAX': 'cosmetics',
    'A3_ROW_OFF': 'cosmetics',
    'A9_COUNT': 'areatargets',
    'A9_ERROR': 'areatargets',
    'A9_ROWS': 'areatargets',
    'A9_ROW_MAX': 'areatargets',
    'ACCOUNT_PIN': 'identity',
    'ACQ_GATE': 'shop',
    'ACQ_RECORD': 'shop',
    'ANNOUNCE': 'lobbymessage',
    'ANNOUNCE_KIND': 'lobbymessage',
    'ANSWER_0137': 'resume',
    'ANSWER_013D': 'withdraw',
    'ANSWER_0156': 'battlegroups',
    'ANSWER_0159': 'scriptcall',
    'ANSWER_015E': 'warmap',
    'ANSWER_0160': 'warmap',
    'ANSWER_0162': 'battlemaps',
    'ANSWER_0169': 'shop',
    'ANSWER_0175': 'servicerecord',
    'ANSWER_017E': 'shop',
    'ANSWER_018D': 'missionlist',
    'ANSWER_LOBAPI': 'charselect',
    'ANSWER_MOVE': 'move',
    'AREA_ACCESS': 'permits',
    'AREA_CHANGE': 'areachange',
    'AREA_CHANGE_LEN': 'areachange',
    'AREA_CHANGE_MAPNO': 'areachange',
    'AREA_CHANGE_STRICT': 'areachange',
    'AREA_CHANGE_ZONE_OFF': 'areachange',
    'AREA_CONTROL': 'areatargets',
    'AREA_FLAG': 'areatargets',
    'AREA_OPEN_LEN': 'permits',
    'AREA_OPEN_OFF': 'permits',
    'AREA_PASS_TIER_CLASS': 'permits',
    'AREA_PERMIT_OFF': 'permits',
    'AREA_TARGET': 'areatargets',
    'AREA_TARGETS': 'areatargets',
    'BATTLE_BOUNDS': 'missionblock',
    'BATTLE_BOUNDS_SPEC': 'missionblock',
    'BATTLE_CAST_HOLD': 'squad',
    'BATTLE_DEATH_END': 'battleend',
    'BATTLE_DUMMY': 'battlepop',
    'BATTLE_DUMMY_AI': 'battlepop',
    'BATTLE_DUMMY_KILL': 'battlepop',
    'BATTLE_DUMMY_KILL_STATUS': 'battlepop',
    'BATTLE_DUMMY_KIND': 'battlepop',
    'BATTLE_DUMMY_NATION': 'battlepop',
    'BATTLE_DUMMY_SIDE': 'battlepop',
    'BATTLE_DUMMY_SPEC': 'battlepop',
    'BATTLE_END': 'battleend',
    'BATTLE_END_CONTRIB': 'battleend',
    'BATTLE_END_EXP': 'battleend',
    'BATTLE_END_SPEC': 'battleend',
    'BATTLE_END_WON': 'battleend',
    'BATTLE_END_WON_SET': 'battleend',
    'BATTLE_ENEMIES': 'squad',
    'BATTLE_ENEMIES_SPEC': 'squad',
    'BATTLE_FIRE_RELAY': 'squad',
    'BATTLE_GATE_KIND': 'battlepop',
    'BATTLE_GATE_POP': 'battlepop',
    'BATTLE_GROUPS': 'battlegroups',
    'BATTLE_GROUPS_MADE': 'battlegroups',
    'BATTLE_HIT': 'battleend',
    'BATTLE_HIT_ECHO': 'squad',
    'BATTLE_HOST': 'addressing',
    'BATTLE_KILL_WINDOW': 'rooms',
    'BATTLE_MAPS': 'battlemaps',
    'BATTLE_OBJECTIVE': 'battleend',
    'BATTLE_OBJECTIVE_SPEC': 'battleend',
    'BATTLE_PARTS': 'popparts',
    'BATTLE_PORT': 'addressing',
    'BATTLE_POS': 'battlepop',
    'BATTLE_POS_SPEC': 'battlepop',
    'BATTLE_ROOM_WANZER': 'rooms',
    'BATTLE_SEEN': 'squad',
    'BATTLE_SQUADS': 'squad',
    'BATTLE_START': 'battleend',
    'BATTLE_START_TIME': 'missionblock',
    'BATTLE_STATE': 'referee',
    'BRIEFING_ZONES': 'move',
    'BUILD': 'room',
    'CEASEFIRE': 'servicerecord',
    'CEASEFIRE_CONTRIB_PCT': 'servicerecord',
    'CEASEFIRE_DAYS': 'servicerecord',
    'CEASEFIRE_MP_DAYS': 'servicerecord',
    'CHARSEL': 'charselect',
    'CHAR_STORE': 'charstore',
    'CHAR_WIRE_BASE': 'charlist',
    'CHK_OFF': 'packet',
    'CITY_ENTRY_OFF': 'citytable',
    'CITY_ID_BASE': 'citytable',
    'CITY_RANK': 'citytable',
    'CITY_ROW_LEN': 'citytable',
    'CITY_ROW_MAX': 'citytable',
    'CITY_ROW_OFF': 'citytable',
    'CITY_TABLE': 'citytable',
    'CITY_TABLE_BLOCK': 'citytable',
    'CITY_TABLE_LEN': 'citytable',
    'CITY_TABLE_OFF': 'citytable',
    'CLASS_CURVE': 'classes',
    'CLASS_EXP': 'classes',
    'CLASS_KIND': 'classes',
    'CLASS_LEVEL': 'classes',
    'CLASS_NAMES': 'classes',
    'CLASS_ROWS': 'classes',
    'CLASS_ROW_LEN': 'classes',
    'CLASS_TABLE': 'classes',
    'CLIENT_RECV_BUF': 'udpconfig',
    'CLIENT_REQUESTS': 'pushes',
    'CLIENT_RX_BUFFER': 'packet',
    'CLIENT_SCRIPT_NO': 'zoneentry',
    'CLIENT_SCRIPT_SWEEP': 'zoneentry',
    'CMD_BM_FIRE': 'squad',
    'CMD_BM_HITLIST': 'squad',
    'CMD_BM_MOVE_BATCH': 'squad',
    'CMD_BM_MOVE_ONE': 'squad',
    'CONTENT_AUTH': 'packet',
    'CONTENT_ID': 'packet',
    'COSMETICS': 'cosmetics',
    'COSMETIC_PRICE': 'cosmetics',
    'COSMETIC_SHOP': 'cosmetics',
    'COSMETIC_TSV': 'cosmetics',
    'COUNTER_BONUS_HS': 'warmap',
    'COUNTER_MISSION': 'warmap',
    'CRED_LEN': 'packet',
    'CRED_LEN_PS2': 'packet',
    'CRED_REPLY_LEN': 'handshake',
    'CRYPT_OFF': 'packet',
    'DAY': 'servicerecord',
    'ECON_STORE_KEYS': 'economy',
    'ENDPOINT_LEN': 'addressing',
    'EP1_OFF': 'addressing',
    'EP2_OFF': 'addressing',
    'EP_0153_NET': 'addressing',
    'EVENTS_TSV': 'scriptcall',
    'EVENT_RULES': 'scriptcall',
    'FACE_SIGN': 'npccast',
    'FAIL_CODE': 'charselect',
    'FIELDS_01AD': 'squadron',
    'FIELD_18': 'zoneentry',
    'FIELD_1C': 'zoneentry',
    'FIELD_A_OFF': 'handshake',
    'FILL_0153': 'zoneentry',
    'FILL_01AD': 'squadron',
    'FLAGS_PLAIN_SUMMED': 'packet',
    'FLAG_CHECKSUM': 'packet',
    'FLAG_ENCRYPTED': 'packet',
    'FMO_DB': 'charstore',
    'FREE_SLOT_ID': 'charlist',
    'FZ_RECAST': 'npccast',
    'FZ_REKEY': 'npccast',
    'G174_BODY_LEN': 'grouplogin',
    'G174_ENDPOINT': 'grouplogin',
    'G174_ID': 'grouplogin',
    'G174_INFO88': 'grouplogin',
    'G174_TYPE': 'grouplogin',
    'G190_GATE': 'groupchannel',
    'G190_IP': 'groupchannel',
    'G190_KEY': 'groupchannel',
    'G190_MODE': 'groupchannel',
    'G190_PORT': 'groupchannel',
    'G190_STATUS_BIT0': 'groupchannel',
    'G190_TAG': 'groupchannel',
    'G190_VOICE': 'groupchannel',
    'G191_BLOB_FROM': 'groupchannel',
    'GROUP_ACK_IDS': 'battlegroups',
    'GROUP_ATTACH': 'grouplogin',
    'GROUP_BLOB_UPDATE_CMD': 'roomrelay',
    'GROUP_BOARD': 'community',
    'GROUP_BOARD_LOG': 'community',
    'GROUP_BOARD_MARK': 'community',
    'GROUP_COUNT': 'addressing',
    'GROUP_CREATOR_ACCOUNT': 'battlegroups',
    'GROUP_ENDED_REASONS': 'pushes',
    'GROUP_ENTRY_LEN': 'grouplogin',
    'GROUP_HOST': 'addressing',
    'GROUP_KEY': 'groupchannel',
    'GROUP_LEADER_MODE': 'groupchannel',
    'GROUP_MEMBERS': 'groupchannel',
    'GROUP_NAME_LEN': 'groupchannel',
    'GROUP_OF': 'groupchannel',
    'GROUP_OFF': 'grouplogin',
    'GROUP_OP_NAMES': 'battlegroups',
    'GROUP_POP': 'groupchannel',
    'GROUP_POP_CMD': 'groupchannel',
    'GROUP_POP_FLAGS': 'groupchannel',
    'GROUP_POP_FLAGS_OFF': 'groupchannel',
    'GROUP_POP_KEY': 'groupchannel',
    'GROUP_POP_LEADER': 'groupchannel',
    'GROUP_POP_LEADER_OFF': 'groupchannel',
    'GROUP_POP_NAME1_OFF': 'groupchannel',
    'GROUP_POP_NAME2_OFF': 'groupchannel',
    'GROUP_PORT': 'addressing',
    'GROUP_READY': 'groupchannel',
    'GROUP_SLOTS': 'grouplogin',
    'GROUP_SORTIE': 'groupchannel',
    'GROUP_TABLES': 'groupchannel',
    'GROUP_TYPE': 'addressing',
    'GROUP_VOICE_CMD': 'roomrelay',
    'GROUP_VOICE_TO': 'roomrelay',
    'GRP_ENDPOINT': 'grouplogin',
    'GRP_GATE': 'grouplogin',
    'GRP_ID': 'grouplogin',
    'GRP_INFO88': 'grouplogin',
    'GRP_TYPE': 'grouplogin',
    'G_FLAG_CONT': 'groupchannel',
    'G_FLAG_LISTED': 'groupchannel',
    'G_FLAG_READY': 'groupchannel',
    'HANGAR': 'move',
    'HANGAR_BAY_DEPTH': 'hangar',
    'HANGAR_BAY_SIZE': 'hangar',
    'HANGAR_BAY_TYPE': 'hangar',
    'HANGAR_OWNER_F18': 'hangar',
    'HANGAR_PW_LEN': 'move',
    'HANGAR_REQUIRED_KEYS': 'hangar',
    'HANGAR_RESIDENTS': 'hangar',
    'HDR': 'packet',
    'HDR_TIME': 'sortie',
    'HELLO_ACK': 'popself',
    'HELLO_ACK_ON': 'popself',
    'HELLO_ACK_SPEC': 'popself',
    'HOLD': 'wirelog',
    'HQ_MARKS': 'npccast',
    'HQ_SE_MARKS': 'npccast',
    'IDENTITY_TTL': 'identity',
    'INFO88_LEN': 'grouplogin',
    'INSIGNIA': 'squadron',
    'INSIGNIA_BLOCK': 'squadron',
    'INSIGNIA_COUNT_OFF': 'squadron',
    'INSIGNIA_LIST_LEN': 'squadron',
    'INSIGNIA_MAX': 'squadron',
    'INSIGNIA_OFFER': 'squadron',
    'INSIGNIA_PUSH': 'squadron',
    'INSIGNIA_ROW_LEN': 'squadron',
    'INSIGNIA_ROW_OFF': 'squadron',
    'INSIGNIA_SET_GROUP': 'squadron',
    'INSIGNIA_SET_ID': 'squadron',
    'INSIGNIA_TSV': 'squadron',
    'INVENTORY_FROM_SETUPS': 'inventory',
    'INV_ENTRY_LEN': 'inventory',
    'INV_MAX': 'inventory',
    'ITEM_FAIL_SPECIAL': 'shop',
    'ITEM_ID': 'inventory',
    'ITEM_KIND': 'inventory',
    'ITEM_RECORD_LEN': 'shop',
    'ITEM_SERIAL_HI': 'inventory',
    'ITEM_SERIAL_LO': 'inventory',
    'JOIN_SECTOR': 'battlegroups',
    'KEY_POLCORE_LEN': 'packet',
    'KILL_BONUS_HS': 'battleend',
    'KILL_CONTRIB': 'battleend',
    'KILL_EXP': 'battleend',
    'LIST_COUNT': 'charlist',
    'LIST_ENTRY_LEN': 'charlist',
    'LIST_LAST': 'charlist',
    'LIST_NAME': 'charlist',
    'LIST_NATION': 'charlist',
    'LIST_REPLY_LEN': 'charlist',
    'LIST_SLOTS': 'charlist',
    'LIVE_SESSIONS': 'trade',
    'LOBAPI': 'lobapi',
    'LOBBY_PUSH_ALL': 'pushes',
    'LOBBY_PUSH_DIRECT': 'pushes',
    'LOBBY_PUSH_IDS': 'pushes',
    'LOBBY_PUSH_TABLE1': 'pushes',
    'LOBBY_PUSH_TABLE2': 'pushes',
    'LOG_DIR': 'wirelog',
    'M16D_CHOICE': 'move',
    'M16D_FIELD_00': 'move',
    'M16D_FIELD_04': 'move',
    'M16D_NAME_A': 'move',
    'M16D_NAME_B': 'move',
    'M16D_NUMBER': 'move',
    'M18E_MODE': 'missionlist',
    'M18E_RECORDS': 'missionlist',
    'M18E_REC_COUNT': 'missionlist',
    'M18E_REC_LEN': 'missionlist',
    'M1C1_BLOCK': 'missionblock',
    'M1C1_BLOCK_LEN': 'missionblock',
    'M1C1_TAIL_U32': 'missionblock',
    'MAPKIND': 'zoneentry',
    'MAPKIND_BANDS': 'zoneentry',
    'MAPKIND_PS2': 'zoneentry',
    'MAPKIND_SWEEP': 'zoneentry',
    'MAPNO': 'zoneentry',
    'MAPNO_PS2': 'zoneentry',
    'MAPNO_SWEEP': 'zoneentry',
    'MARK_BASE_DEFAULT': 'lobapi',
    'MARK_LOBAPI': 'lobapi',
    'MAX_PAYLOAD': 'packet',
    'MB_AREA_LIMIT': 'missionblock',
    'MB_AREA_MAXX': 'missionblock',
    'MB_AREA_MAXZ': 'missionblock',
    'MB_AREA_MINX': 'missionblock',
    'MB_AREA_MINZ': 'missionblock',
    'MB_ARMYDIRECT': 'missionblock',
    'MB_BATTLETICKET': 'missionblock',
    'MB_BATTLE_SIDE': 'missionblock',
    'MB_BGCOSTMAX': 'missionblock',
    'MB_CLIENTSCRIPTNO': 'missionblock',
    'MB_FLAGS': 'missionblock',
    'MB_LD': 'missionblock',
    'MB_LEADERID': 'missionblock',
    'MB_MAPINPLAYERNUM': 'missionblock',
    'MB_MAPNO': 'missionblock',
    'MB_MUSICNO': 'missionblock',
    'MB_NPCMAX': 'missionblock',
    'MB_NPCSCRIPTNUM': 'missionblock',
    'MB_PENALTY': 'missionblock',
    'MB_RECTDATA': 'missionblock',
    'MB_RECTDATACNT': 'missionblock',
    'MB_RECTGROUPCNT': 'missionblock',
    'MB_RECT_MINX': 'missionblock',
    'MB_RECT_MINZ': 'missionblock',
    'MB_RECT_SIZEX': 'missionblock',
    'MB_RECT_SIZEZ': 'missionblock',
    'MB_RECT_STRIDE': 'missionblock',
    'MB_START_GAMETIME': 'missionblock',
    'MB_TIMELIMIT': 'missionblock',
    'MB_TOTALBGCOST': 'missionblock',
    'MEMBER_CHECK': 'popself',
    'MEMBER_CHECK_HIT': 'popself',
    'MEMBER_CHECK_MISS': 'popself',
    'MEMBER_LOOKUP': 'identity',
    'MEMBER_WINDOW': 'identity',
    'MINT_ADDS': 'shop',
    'MINT_RECORDS': 'shop',
    'MINT_TOTAL': 'shop',
    'MISSIONS': 'progress',
    'MISSIONS_TSV': 'progress',
    'MISSION_ACCEPT': 'missionboard',
    'MISSION_ACTIVE': 'missionboard',
    'MISSION_AREA': 'missionblock',
    'MISSION_AREA_SPEC': 'missionblock',
    'MISSION_BATTLETICKET': 'missionblock',
    'MISSION_BGCOSTMAX': 'missionblock',
    'MISSION_DEADLINE': 'missionboard',
    'MISSION_DEADLINE_AREA': 'areatargets',
    'MISSION_DEADLINE_SECTOR': 'warmap',
    'MISSION_FEE': 'missionboard',
    'MISSION_LEADER': 'missionblock',
    'MISSION_LIST_FIELDS': 'missionlist',
    'MISSION_LIST_MODE': 'missionlist',
    'MISSION_LIST_ROWS': 'missionlist',
    'MISSION_MAPNO': 'missionblock',
    'MISSION_MAP_ICON': 'warmap',
    'MISSION_REFUSALS': 'missionboard',
    'MISSION_REPORT': 'missionboard',
    'MISSION_STATE': 'missionboard',
    'MISSION_TIME': 'missionblock',
    'MISSION_TOTALBGCOST': 'missionblock',
    'MISSION_WINS': 'warmap',
    'ML_KEY': 'missionlist',
    'ML_NAME': 'missionlist',
    'ML_NAME_MAX': 'missionlist',
    'MODEL_FROM_ROSTER': 'popself',
    'MODEL_SPEC': 'popsweep',
    'MOVE_CATEGORY_BRIEFING': 'move',
    'MOVE_CATEGORY_NAMES': 'move',
    'MOVE_CATEGORY_ROOM': 'move',
    'MOVE_IDS_OFF': 'move',
    'MOVE_KIND_BRIEFING': 'move',
    'MOVE_LIST': 'move',
    'MOVE_LIST_BRIEFING': 'move',
    'MOVE_LIST_ROOM': 'move',
    'MOVE_MAPNO': 'move',
    'MOVE_NAME_LEN': 'move',
    'MOVE_PEOPLE_OFF': 'move',
    'MOVE_REQ_LEN': 'move',
    'MOVE_SLOTS': 'move',
    'MOVE_UI_ROWS': 'move',
    'MR_LIMIT': 'missionboard',
    'MR_RESULT': 'missionboard',
    'MR_START': 'missionboard',
    'MR_STATE': 'missionboard',
    'MSG_0132_REPLY': 'inventory',
    'MSG_0132_REQ': 'inventory',
    'MSG_0150_REPLY': 'zoneentry',
    'MSG_0150_REQ': 'zoneentry',
    'MSG_0154_REPLY': 'grouplogin',
    'MSG_0154_REQ': 'grouplogin',
    'MSG_0156_REQ': 'battlegroups',
    'MSG_0157_REQ': 'battlegroups',
    'MSG_0158_REPLY': 'battlegroups',
    'MSG_0159_REQ': 'scriptcall',
    'MSG_015E_REQ': 'warmap',
    'MSG_015F_REPLY': 'warmap',
    'MSG_0160_REQ': 'warmap',
    'MSG_0161_REPLY': 'warmap',
    'MSG_0162_REQ': 'battlemaps',
    'MSG_0163_REPLY': 'battlemaps',
    'MSG_0165_REPLY': 'inventory',
    'MSG_0165_REQ': 'inventory',
    'MSG_0175_REQ': 'servicerecord',
    'MSG_0176_REPLY': 'servicerecord',
    'MSG_01F4_REQ': 'battlemaps',
    'MSG_01F5_REPLY': 'battlemaps',
    'MSG_01F6_REQ': 'battlemaps',
    'MSG_ACQUIRE': 'shop',
    'MSG_ACQUIRE_REPLY': 'shop',
    'MSG_AREA_CHANGE_REQ': 'areachange',
    'MSG_AREA_TARGETS_REPLY': 'areatargets',
    'MSG_AREA_TARGETS_REQ': 'areatargets',
    'MSG_BATTLE_END': 'battleend',
    'MSG_BATTLE_WITHDRAW': 'withdraw',
    'MSG_CHANGE_NATIONS': 'charselect',
    'MSG_CITY_TABLE': 'citytable',
    'MSG_CREDENTIALS': 'handshake',
    'MSG_CRED_REPLY': 'handshake',
    'MSG_FAIL': 'charselect',
    'MSG_FEE_PUSH': 'pushes',
    'MSG_GAME_HELLO': 'handshake',
    'MSG_GROUP_ATTACH': 'grouplogin',
    'MSG_GROUP_COMMENT_REPLY': 'battlegroups',
    'MSG_GROUP_COMMENT_REQ': 'battlegroups',
    'MSG_GROUP_ENDED': 'pushes',
    'MSG_GROUP_LOGIN_NOTIFY': 'pushes',
    'MSG_HANDSHAKE_OK': 'handshake',
    'MSG_HANGAR_PW': 'move',
    'MSG_INSIGNIA_LIST': 'squadron',
    'MSG_INSIGNIA_SET': 'squadron',
    'MSG_ITEM_ANNOUNCE': 'pushes',
    'MSG_ITEM_BUY': 'shop',
    'MSG_ITEM_BUY_REPLY': 'shop',
    'MSG_ITEM_SELL': 'shop',
    'MSG_KEEPALIVE': 'charselect',
    'MSG_LIST_REPLY': 'charlist',
    'MSG_LIST_REQ': 'charlist',
    'MSG_LOBBY_MESSAGE': 'lobbymessage',
    'MSG_LOCAL_HELLO': 'timesync',
    'MSG_LOGOUT_REQ': 'move',
    'MSG_LOG_UPLOAD': 'charselect',
    'MSG_MEMBER_CHECK_REQ': 'move',
    'MSG_MISSION_ACCEPT': 'missionboard',
    'MSG_MISSION_ACCEPT_REPLY': 'missionboard',
    'MSG_MISSION_CANCEL': 'missionboard',
    'MSG_MISSION_CANCEL_REPLY': 'missionboard',
    'MSG_MISSION_LIST_REPLY': 'missionlist',
    'MSG_MISSION_LIST_REQ': 'missionlist',
    'MSG_MISSION_REPLY': 'missionblock',
    'MSG_MISSION_REPORT': 'missionboard',
    'MSG_MISSION_REPORT_REPLY': 'missionboard',
    'MSG_MISSION_REQ': 'missionblock',
    'MSG_MOVE_LIST_REPLY': 'move',
    'MSG_MOVE_LIST_REQ': 'move',
    'MSG_MOVE_REQ': 'move',
    'MSG_NAMES': 'msgnames',
    'MSG_NATION_REQ': 'charselect',
    'MSG_ORDER_REQ': 'areatargets',
    'MSG_PARTS_STOCK': 'partsstock',
    'MSG_PLAYTIME_REPLY': 'move',
    'MSG_PLAYTIME_REQ': 'move',
    'MSG_RESULT_PUSH': 'resultpush',
    'MSG_RESUME_REPLY': 'resume',
    'MSG_RESUME_REQ': 'resume',
    'MSG_RESUPPLY': 'pushes',
    'MSG_SESSION_START': 'handshake',
    'MSG_SETUP_SAVE': 'shop',
    'MSG_SORTIE_GO': 'sortiepush',
    'MSG_SORTIE_PUSH': 'sortiepush',
    'MSG_SORTIE_REPLY': 'sortie',
    'MSG_SORTIE_REQ': 'sortie',
    'MSG_SQUADRON_ACTIVATE': 'squadron',
    'MSG_SQUADRON_INSIGNIA': 'squadron',
    'MSG_SQUADRON_ROW': 'squadron',
    'MSG_START_GAME': 'handshake',
    'MSG_START_GAME_OK': 'handshake',
    'MSG_START_STATUS': 'status',
    'MSG_TIME_REPLY': 'timesync',
    'MSG_TIME_REQ': 'timesync',
    'MSG_TIME_SYNC': 'timesync',
    'MSG_TRADE_ACCEPT': 'trade',
    'MSG_TRADE_OFFER': 'trade',
    'MSG_TRADE_OK': 'trade',
    'MSG_TRADE_POLL': 'trade',
    'MSG_TRADE_PUSH': 'trade',
    'MSG_TRADE_START': 'trade',
    'MSG_TRADE_STATE': 'trade',
    'MSG_TRADE_UPDATE': 'trade',
    'MSG_VERSION': 'handshake',
    'MSG_ZONE_CONTROL': 'zonecontrol',
    'MSN': 'community',
    'MSN_END_OPS': 'community',
    'MSN_FIELDS': 'community',
    'MSN_MARK': 'community',
    'MSN_ON': 'community',
    'MSN_PROBE_ROWS': 'community',
    'MSN_REFUSE_CODE': 'community',
    'MSN_ROWS': 'community',
    'MSN_UNKNOWN': 'community',
    'MSN_WINS': 'warmap',
    'MSN_ZONES': 'sectorwins',
    'MUSIC_NO': 'zoneentry',
    'NAME_TAKEN_CODE': 'charstore',
    'NAME_UNIQUE': 'charstore',
    'NATION': 'charlist',
    'NATION_CHANGE_TOGGLE': 'charselect',
    'NATION_ENABLE': 'charselect',
    'NATION_PER_CHARACTER': 'zoneentry',
    'NATION_POP': 'charselect',
    'NATION_SIDE': 'popnation',
    'NEXT_HOST': 'addressing',
    'NEXT_PORT': 'addressing',
    'NPC_CKIND_OVERRIDE': 'npccast',
    'NPC_LAYOUT': 'npccast',
    'NUL': 'charselect',
    'OBJECTIVE': 'battleend',
    'OBJECTIVE_SPEC': 'battleend',
    'OCC_RECAST': 'npccast',
    'ORDER_BODY': 'areatargets',
    'ORDER_COMMENT': 'areatargets',
    'ORDER_COMMENT_LEN': 'areatargets',
    'ORDER_FIELDS': 'areatargets',
    'ORDER_KEEP': 'areatargets',
    'ORDER_NAME': 'areatargets',
    'ORDER_NAME_LEN': 'areatargets',
    'OUTLOOK': 'servicerecord',
    'PARTS_STOCK': 'partsstock',
    'PARTS_STOCK_BODY_OFF': 'partsstock',
    'PARTS_STOCK_HDR': 'partsstock',
    'PARTS_STOCK_SPEC': 'partsstock',
    'PART_TABLE_COUNT': 'partsstock',
    'PASS_HQ': 'permits',
    'PASS_KEYS': 'permits',
    'PASS_KIND': 'permits',
    'PASS_ZONE_KIND': 'permits',
    'PAY_BASE': 'servicerecord',
    'PAY_CITY': 'servicerecord',
    'PAY_HEADER': 'servicerecord',
    'PAY_KILL': 'warmap',
    'PAY_KINDS': 'servicerecord',
    'PAY_MISSION': 'missionboard',
    'PEER_ACKED': 'peerlink',
    'PEER_HELLO': 'peerlink',
    'PEER_KEEPALIVE': 'room',
    'PEER_LINK': 'room',
    'PEER_PING': 'peerlink',
    'PEER_PONG': 'peerlink',
    'PEER_TAG_BASE': 'room',
    'PERMIT': 'permits',
    'PERMIT_ALL': 'permits',
    'PERMIT_RANKS': 'permits',
    'PERMIT_RANKS_RAW': 'permits',
    'PERMIT_RAW': 'permits',
    'PILOTPOS': 'zoneentry',
    'PILOTPOS_SWEEP': 'zoneentry',
    'PILOT_DEATHS': 'battleend',
    'PLACES': 'move',
    'PLACE_CAP': 'move',
    'PLACE_CATEGORY_KINDS': 'move',
    'PLACE_KIND_NAMES': 'move',
    'PLAYTIME': 'move',
    'PLAYTIME_BASE': 'move',
    'POP': 'popsweep',
    'POP_AFTER': 'popself',
    'POP_AI_BRAIN': 'battlepop',
    'POP_AI_OWNER': 'battlepop',
    'POP_BATTLE': 'battlepop',
    'POP_BATTLE_SPEC': 'battlepop',
    'POP_CLIENT_KIND_KNOB': 'popself',
    'POP_LOOK': 'poplook',
    'POP_LOOK_DEFER': 'poplook',
    'POP_LOOK_FIELDS': 'poplook',
    'POP_LOOK_FIXED': 'poplook',
    'POP_MODEL': 'popsweep',
    'POP_MODEL_SWEEP': 'popsweep',
    'POP_NAME1': 'popself',
    'POP_NAME2': 'popself',
    'POP_NAMES': 'npcroster',
    'POP_NATION_KNOB': 'popnation',
    'POP_NPC': 'npccast',
    'POP_NPC_CLIENT_KIND': 'npcroster',
    'POP_NPC_COL': 'npccast',
    'POP_NPC_COL_DEFAULT': 'npccast',
    'POP_NPC_COL_NAMES': 'npccast',
    'POP_NPC_COL_SPEC': 'npccast',
    'POP_NPC_COL_USN': 'npccast',
    'POP_NPC_COL_USN_NAMES': 'npccast',
    'POP_NPC_FZ': 'npccast',
    'POP_NPC_FZ_NAMES': 'npccast',
    'POP_NPC_FZ_SPEC': 'npccast',
    'POP_NPC_FZ_USN': 'npccast',
    'POP_NPC_FZ_USN_NAMES': 'npccast',
    'POP_NPC_NAMES': 'npccast',
    'POP_NPC_OCC': 'npccast',
    'POP_NPC_OCC_NAMES': 'npccast',
    'POP_NPC_OCC_SPEC': 'npccast',
    'POP_NPC_OCC_USN': 'npccast',
    'POP_NPC_OCC_USN_NAMES': 'npccast',
    'POP_NPC_RELOOK': 'poplook',
    'POP_NPC_REPOP': 'poplook',
    'POP_NPC_SPEC': 'npccast',
    'POP_NPC_TARGETABLE': 'npcroster',
    'POP_NPC_USN': 'npccast',
    'POP_NPC_USN_NAMES': 'npccast',
    'POP_NPC_USN_SPEC': 'npccast',
    'POP_POS': 'popsweep',
    'POP_POS_MAP': 'popsweep',
    'POP_POS_SWEEP': 'popsweep',
    'POP_ROSTER_NAME': 'popself',
    'POP_SEX': 'popself',
    'POP_SEX_FROM_ROSTER': 'popself',
    'POP_SEX_SOURCE': 'popnames',
    'POP_SEX_SWEEP': 'popself',
    'POP_SPEC': 'popself',
    'POP_TYPE_SWEEP': 'popsweep',
    'PORT': 'wirelog',
    'POS_LOG_EVERY': 'udpconfig',
    'PROGRESS_ADVANCE': 'progress',
    'PROGRESS_RANK_FOLLOW': 'progress',
    'PS2_GATE': 'zoneentry',
    'PS2_MAPNOS_UNION': 'zoneentry',
    'PS2_TYPE1': 'zoneentry',
    'PS2_TYPE1_050324': 'zoneentry',
    'PS2_VALID_MAPKINDS': 'zoneentry',
    'PS2_VALID_MAPNOS': 'zoneentry',
    'PUSH_NOTES': 'pushes',
    'PUSH_PROBE': 'pushes',
    'PUSH_SESSION_START': 'handshake',
    'Q139_AREA': 'sortie',
    'Q139_BGFLAG': 'sortie',
    'Q139_CHAR48': 'sortie',
    'Q139_CHAR48_LEN': 'sortie',
    'Q139_CREATE': 'sortie',
    'Q139_ID': 'sortie',
    'Q139_INFOID': 'sortie',
    'Q139_RESUME': 'sortie',
    'Q1AD_DWORDS': 'squadron',
    'Q1AD_LEN': 'squadron',
    'QUEUE_SEQ': 'pushes',
    'R13A_BLOCK': 'sortie',
    'R13A_ENDPOINT': 'sortie',
    'R13A_INFO88': 'sortie',
    'R13A_INFO88_LEN': 'sortie',
    'R14E_BLOCK': 'sortiepush',
    'R14E_DEST': 'sortiepush',
    'R14E_DEST_LEN': 'sortiepush',
    'R14E_ENDPOINT': 'sortiepush',
    'R14E_FLAGS': 'sortiepush',
    'R14E_ID': 'sortiepush',
    'R14E_INFO88': 'sortiepush',
    'R14E_TIME': 'sortiepush',
    'R153_ENDPOINT': 'zoneentry',
    'R153_FIELD_18': 'zoneentry',
    'R153_FIELD_1C': 'zoneentry',
    'R153_INFO88': 'zoneentry',
    'R153_MAPKIND': 'zoneentry',
    'R153_SETUP': 'zoneentry',
    'RANK_CAPTAIN': 'servicerecord',
    'RANK_COLONEL': 'servicerecord',
    'RANK_FIRST_SERGEANT': 'servicerecord',
    'RANK_FROM_CONTRIB': 'ranks',
    'RANK_GROUP': 'ranks',
    'RANK_LADDER': 'ranks',
    'RANK_MAJOR': 'servicerecord',
    'RANK_MAX_EARNABLE': 'ranks',
    'RANK_PAY': 'ranks',
    'RC4': 'packet',
    'REFEREE': 'battlepop',
    'REGIONS': 'packet',
    'REGRANT_0159': 'scriptcall',
    'RELEASE_DEFAULTS': 'defaults',
    'REPLY_0133_LEN': 'inventory',
    'REPLY_013A_LEN': 'sortie',
    'REPLY_014A_LEN': 'status',
    'REPLY_014E_LEN': 'sortiepush',
    'REPLY_0153_LEN': 'zoneentry',
    'REPLY_0155_LEN': 'grouplogin',
    'REPLY_0158_JOIN_LEN': 'battlegroups',
    'REPLY_0163_LEN': 'groupchannel',
    'REPLY_0166_LEN': 'inventory',
    'REPLY_016B_LEN': 'shop',
    'REPLY_016F_LEN': 'move',
    'REPLY_0183_LEN': 'move',
    'REPLY_018E_LEN': 'missionlist',
    'REPLY_018F_LEN': 'missionboard',
    'REPLY_019D_LEN': 'charselect',
    'REPLY_01C1_LEN': 'missionblock',
    'REQ_0139_LEN': 'sortie',
    'RESULT_CONTRIB': 'resultpush',
    'RESULT_MONEY': 'resultpush',
    'RESULT_PUSH': 'resultpush',
    'RESUME_RES_BASE': 'resume',
    'RESUME_RES_COUNT': 'resume',
    'RESUME_RES_INDEX': 'resume',
    'REVIEW': 'servicerecord',
    'REVIEW_CAPS': 'servicerecord',
    'REVIEW_CAPS_SPEC': 'servicerecord',
    'REVIEW_DAYS': 'servicerecord',
    'REVIEW_PROMOTE': 'servicerecord',
    'ROOM': 'room',
    'ROOM_ALIAS_BASE': 'room',
    'ROOM_DEPOP': 'room',
    'ROOM_DEPOP_STATUS': 'room',
    'ROOM_LOG_EVERY': 'room',
    'ROOM_LOG_FIRST': 'room',
    'ROOM_MAPS': 'move',
    'ROOM_MIN_INTERVAL': 'room',
    'ROOM_PEER_KEY': 'room',
    'ROOM_SAME_MAP': 'room',
    'ROOM_SAME_ZONE': 'room',
    'ROOM_SETUP_SLOTS': 'room',
    'ROOM_TTL': 'room',
    'ROOM_TYPE': 'room',
    'RemoteStream': 'worldchannel',
    'S018E_ROWS': 'missionlist',
    'S018E_SHORT_LEN': 'missionlist',
    'S14A_ACTIVE_SETUP': 'status',
    'S14A_B8B4': 'status',
    'S14A_B8B5': 'status',
    'S14A_BE1A': 'status',
    'S14A_BLOCK': 'status',
    'S14A_BLOCK2': 'status',
    'S14A_BLOCK2_LEN': 'status',
    'S14A_BLOCK3': 'status',
    'S14A_BLOCK3_LEN': 'status',
    'S14A_BLOCK_LEN': 'status',
    'S14A_CLASS_TABLE': 'classes',
    'S14A_CONTRIB': 'status',
    'S14A_FIRST': 'status',
    'S14A_FLAGS11': 'status',
    'S14A_FLAGS11_LEN': 'status',
    'S14A_HANGAR_PW': 'status',
    'S14A_HANGAR_PW_LEN': 'status',
    'S14A_LAST': 'status',
    'S14A_MONEY': 'status',
    'S14A_MP': 'status',
    'S14A_NAME_LEN': 'status',
    'S14A_NATION': 'status',
    'S14A_OWNED': 'status',
    'S14A_OWNED_LEN': 'status',
    'S14A_RANK': 'status',
    'S14A_RANK_GROUP': 'classes',
    'S14A_SEX': 'status',
    'S14A_W7604': 'status',
    'S14A_W7608': 'status',
    'S14A_WFC8': 'status',
    'S14B_BODY_LEN': 'lobbymessage',
    'S14B_FLAG': 'lobbymessage',
    'S14B_KIND': 'lobbymessage',
    'S14B_NAME1': 'lobbymessage',
    'S14B_NAME2': 'lobbymessage',
    'S14B_SENDER': 'lobbymessage',
    'S14B_TEXT': 'lobbymessage',
    'S14B_TEXT_MAX': 'lobbymessage',
    'S14C_AUTO_DISBAND': 'battleend',
    'S14C_BLOCK': 'battleend',
    'S14C_BLOCK_LEN': 'battleend',
    'S14C_CLASS_ROWS': 'battleend',
    'S14C_CLASS_ROW_LEN': 'battleend',
    'S14C_CONTRIB_NEW': 'battleend',
    'S14C_CONTRIB_OLD': 'battleend',
    'S14C_CONTROL': 'battleend',
    'S14C_COUNTER': 'battleend',
    'S14C_EXP_MAX': 'battleend',
    'S14C_EXP_ROWS': 'battleend',
    'S14C_EXP_ROW_LEN': 'battleend',
    'S14C_FLAGS': 'battleend',
    'S14C_HANGAR_RANK': 'battleend',
    'S14C_HAS_BLOCK': 'battleend',
    'S14C_JOIN_BASE': 'battleend',
    'S14C_JOIN_PCT': 'battleend',
    'S14C_LEN': 'battleend',
    'S14C_OP_BONUS': 'battleend',
    'S14C_PART_A': 'battleend',
    'S14C_PART_B': 'battleend',
    'S14C_PLATOON_MONEY': 'battleend',
    'S14C_PLATOON_PAYER': 'battleend',
    'S14C_PLATOON_PCT': 'battleend',
    'S14C_REPLAY': 'battleend',
    'S14C_RESULT': 'battleend',
    'S14C_SURV_IDX': 'battleend',
    'S14C_SURV_TABLE': 'battleend',
    'S14C_TAIL': 'battleend',
    'S14C_TAIL_LEN': 'battleend',
    'S14C_VICTORY': 'battleend',
    'S158_ON_SORTIE': 'battlegroups',
    'S158_PLAYERS': 'groupchannel',
    'S158_PLAYERS_N': 'groupchannel',
    'S158_ROW_LEN': 'groupchannel',
    'S158_ROW_NATION': 'groupchannel',
    'S158_SECTOR': 'battlegroups',
    'S159_B418': 'scriptcall',
    'S159_BODY_LEN': 'scriptcall',
    'S159_EVENT': 'scriptcall',
    'S159_NPARAMS': 'scriptcall',
    'S159_PARAMS': 'scriptcall',
    'S15A_B418': 'resultpush',
    'S15A_B419': 'resultpush',
    'S15A_B41A': 'resultpush',
    'S15A_BODY_LEN': 'resultpush',
    'S15A_CONTRIB': 'resultpush',
    'S15A_GRANT': 'resultpush',
    'S15A_ITEM_LEN': 'resultpush',
    'S15A_KEEP_RECORD': 'resultpush',
    'S15A_MAX_ITEMS': 'resultpush',
    'S15A_MONEY': 'resultpush',
    'S15A_N_GRANT': 'resultpush',
    'S15A_N_SPEND': 'resultpush',
    'S15A_OWNED': 'resultpush',
    'S15A_OWNED_CAP': 'resultpush',
    'S15A_OWNED_LEN': 'resultpush',
    'S15A_SPEND': 'resultpush',
    'S15F_BAR_OTHER': 'warmap',
    'S15F_BAR_OWN': 'warmap',
    'S15F_CAP': 'warmap',
    'S15F_COUNT': 'warmap',
    'S15F_ELAPSED': 'warmap',
    'S15F_HEAD_LEN': 'warmap',
    'S15F_ICON': 'warmap',
    'S15F_LIMIT': 'warmap',
    'S15F_ROW_LEN': 'warmap',
    'S15F_SIDE_CAP': 'warmap',
    'S163_MAPROW': 'groupchannel',
    'S163_ON_SORTIE': 'groupchannel',
    'S163_SECTOR': 'groupchannel',
    'S169_PRICE': 'shop',
    'S169_RECORD': 'shop',
    'S169_REC_ID': 'shop',
    'S169_REC_KIND': 'shop',
    'S169_REC_MODE': 'shop',
    'S169_REC_SERIAL': 'shop',
    'S176_B0C': 'servicerecord',
    'S176_BODY_LEN': 'servicerecord',
    'S176_CONTRIB_SHOWN': 'servicerecord',
    'S176_CONTRIB_STORED': 'servicerecord',
    'S176_NEXT_PAYDAY': 'servicerecord',
    'S176_OUTLOOK': 'servicerecord',
    'S176_RANK': 'servicerecord',
    'S176_RANK_NAME': 'servicerecord',
    'S176_ROWS': 'servicerecord',
    'S176_ROW_COUNT': 'servicerecord',
    'S176_ROW_LEN': 'servicerecord',
    'S176_ROW_MAX': 'servicerecord',
    'S176_TOTAL_MONEY': 'servicerecord',
    'S176_TOTAL_MP': 'servicerecord',
    'S178_LEN': 'pushes',
    'S183_SECONDS': 'move',
    'S188_MIN_LEN': 'pushes',
    'S188_MSNLSID': 'pushes',
    'S188_SECTOR': 'pushes',
    'S199_LEN': 'timesync',
    'S19B_FIRST': 'pushes',
    'S19B_ITEM_ID': 'pushes',
    'S19B_ITEM_KIND': 'pushes',
    'S19B_LAST': 'pushes',
    'S19B_LEN': 'pushes',
    'S19B_NAME_LEN': 'pushes',
    'S19B_UNIT': 'pushes',
    'S1A1_COLISEUM_FEE': 'pushes',
    'S1A1_LEN': 'pushes',
    'S1A1_MOD_REFUSED': 'pushes',
    'S1A1_MONEY': 'pushes',
    'S1A1_SORTIE_COST': 'pushes',
    'S1A1_SPECTATOR_FEE': 'pushes',
    'S1A7_COUNT': 'pushes',
    'S1A7_LEN': 'pushes',
    'S1A7_MAX_ROWS': 'pushes',
    'S1A7_MONEY': 'pushes',
    'S1A7_ROWS': 'pushes',
    'S1A7_ROW_FLAG': 'pushes',
    'S1A7_ROW_LEN': 'pushes',
    'S1A7_STOCK_OFF': 'pushes',
    'S1AF_LEN': 'squadron',
    'S1B1_LEN': 'squadron',
    'S1C5_INSIGNIA': 'squadron',
    'S1C5_LEN': 'squadron',
    'S1C5_MONEY': 'squadron',
    'S1F5_BODY_LEN': 'battlemaps',
    'SALARY': 'servicerecord',
    'SALARY_EVERY': 'servicerecord',
    'SALARY_MAX_DAYS': 'servicerecord',
    'SALARY_RAW': 'servicerecord',
    'SECTOR_WINS': 'sectorwins',
    'SECTOR_WINS_KEEP': 'sectorwins',
    'SECTOR_WINS_LEGACY': 'sectorwins',
    'SECTOR_WINS_STORE': 'sectorwins',
    'SEND_HANDSHAKE_OK': 'handshake',
    'SEQ_BIT': 'packet',
    'SEQ_MASK': 'packet',
    'SEQ_MIN': 'packet',
    'SERIAL_LOW_BASE': 'shop',
    'SERVER_KEY_TAIL': 'packet',
    'SERVE_MISSION_BLOCK': 'missionblock',
    'SERVE_MISSION_LIST': 'missionlist',
    'SERVE_SORTIE': 'sortie',
    'SERVE_SQUADRON': 'squadron',
    'SERVE_START_STATUS': 'status',
    'SESSION_START_DELAY': 'handshake',
    'SESSION_TOKEN': 'charstore',
    'SETUP_ENTRY_LEN': 'inventory',
    'SETUP_FILL': 'inventory',
    'SETUP_IN_USE': 'inventory',
    'SETUP_ITEMS': 'inventory',
    'SETUP_ITEM_OFF': 'inventory',
    'SETUP_LEN': 'zoneentry',
    'SETUP_PARTS': 'inventory',
    'SETUP_SLOTS': 'inventory',
    'SETUP_STARTER': 'inventory',
    'SETUP_TAIL_OFF': 'inventory',
    'SETUP_UNIT_IDS': 'room',
    'SE_NO': 'zoneentry',
    'SLOT_TO_ITEM': 'inventory',
    'SORTIE_COST': 'pushes',
    'SORTIE_ENDPOINT': 'sortie',
    'SORTIE_HOST': 'sortie',
    'SORTIE_MAP': 'rooms',
    'SORTIE_MAPNO': 'sortie',
    'SORTIE_PORT': 'sortie',
    'SORTIE_PUSH_DELAY': 'sortiepush',
    'SORTIE_PUSH_DEST': 'sortiepush',
    'SORTIE_PUSH_MAPNO': 'sortiepush',
    'SORTIE_PUSH_TIME': 'sortiepush',
    'SQUADRON_FORMED': 'squadron',
    'SQUADRON_GROUPS': 'squadron',
    'SQUADRON_INSIGNIA': 'squadron',
    'SQUADRON_NATION': 'squadron',
    'SQ_FORMED': 'squadron',
    'SQ_ID_HI': 'squadron',
    'SQ_ID_LO': 'squadron',
    'SQ_INSIGNIA': 'squadron',
    'SQ_IS_FMO': 'squadron',
    'SQ_MY_SLOT': 'squadron',
    'SQ_NATION': 'squadron',
    'SQ_SLOTS': 'squadron',
    'SQ_SLOT_LEN': 'squadron',
    'STARTER_FALLBACK': 'inventory',
    'STARTER_NAMES': 'inventory',
    'STARTER_SETUPS': 'inventory',
    'START_RANK': 'status',
    'STATUS_ACKRANK': 'status',
    'STATUS_ACTIVE_SETUP': 'status',
    'STATUS_CONTRIB': 'status',
    'STATUS_ENV_KNOBS': 'selftests',
    'STATUS_FLAGS': 'status',
    'STATUS_FLAG_BYTES': 'status',
    'STATUS_MARK': 'status',
    'STATUS_MARK_SKIP': 'status',
    'STATUS_MARK_ZERO': 'status',
    'STATUS_MONEY': 'status',
    'STATUS_MP': 'status',
    'STATUS_NAMES': 'status',
    'STATUS_NATION': 'status',
    'STATUS_SEX': 'status',
    'STATUS_SEX_ROSTER': 'status',
    'STATUS_W7604': 'status',
    'STATUS_W7608': 'status',
    'STATUS_WFD4': 'status',
    'SU_CLIENTSCRIPTNO': 'zoneentry',
    'SU_MAPNO': 'zoneentry',
    'SU_MUSICNO': 'zoneentry',
    'SU_PILOTPOS': 'zoneentry',
    'SU_SENO': 'zoneentry',
    'SU_UNITS': 'zoneentry',
    'SU_UNIT_SLOTS': 'zoneentry',
    'Session': 'session',
    'SessionPilotRecord': 'pilotrecord',
    'SessionResume': 'resume',
    'SessionSettlement': 'settlement',
    'SessionSortie': 'sortie',
    'SessionTrade': 'trade',
    'TIME_SYNC': 'timesync',
    'TRADE': 'trade',
    'TRADES': 'trade',
    'TRADE_BLOCK_LEN': 'trade',
    'TRADE_LAST': 'trade',
    'TRADE_MONEY': 'trade',
    'TRADE_MY_BLOCK': 'trade',
    'TRADE_NAME_LEN': 'trade',
    'TRADE_OK': 'trade',
    'TRADE_PARTNER_BLOCK': 'trade',
    'TRADE_PUSH_FIRST': 'trade',
    'TRADE_REFUSE_STATE': 'trade',
    'TRADE_REPLY_FIRST': 'trade',
    'TRADE_SLOT': 'trade',
    'TRADE_SLOTS': 'trade',
    'TRADE_STATE_LEN': 'trade',
    'TRADE_STATE_OFF': 'trade',
    'TRADE_TTL': 'trade',
    'TRAINING_GATE': 'charstore',
    'TYPE1_ON_DISK': 'missionlist',
    'UDP_CHAT_ECHO': 'udpconfig',
    'UDP_DUMP_FIRST': 'udpconfig',
    'UDP_DUMP_NOKEY': 'udpconfig',
    'UDP_ENABLE': 'udpconfig',
    'UDP_HID': 'udpconfig',
    'UDP_HID_BATTLE': 'udpconfig',
    'UDP_HID_ECHO': 'udpconfig',
    'UDP_HID_GROUP': 'udpconfig',
    'UDP_KEY_IDS': 'udpconfig',
    'UDP_MAX_DATAGRAM': 'udpconfig',
    'UDP_SAY': 'udpconfig',
    'UDP_SAY_AFTER': 'udpconfig',
    'UDP_SAY_NAME': 'udpconfig',
    'UNDESTROY_AFTER': 'popself',
    'UNDESTROY_DEPOP_STATUS': 'popself',
    'UNDESTROY_KIND': 'popself',
    'UNSERVED_BY_DESIGN': 'pushes',
    'UNSUBSTITUTED_BAND': 'areachange',
    'VALID_ITEM_KINDS': 'inventory',
    'VALID_MAPNOS': 'zoneentry',
    'WALKED': 'devtool',
    'WAR': 'warstate',
    'WARMAP_ENTRY': 'warmap',
    'WARMAP_FIELDS': 'warmap',
    'WARMAP_MAPS': 'warmap',
    'WARMAP_SECTORS': 'warmap',
    'WAR_FIELDS': 'warstate',
    'WAR_MAP': 'warstate',
    'WIN_CONTRIB': 'battleend',
    'WIN_MONEY': 'battleend',
    'WITHDRAW_TICK_STATE': 'withdraw',
    'WORLD_ENTRY_TTL': 'worldchannel',
    'WORLD_MAPS': 'rooms',
    'WORLD_PART_SLOTS': 'inventory',
    'WORLD_PEERS': 'groupchannel',
    'WORLD_PLACES': 'move',
    'WORLD_ZONES': 'rooms',
    'WorldChannel': 'worldchannel',
    'ZONE_BLOCK': 'zonecontrol',
    'ZONE_BLOCK_OFF': 'zonecontrol',
    'ZONE_CONTROL': 'zonecontrol',
    'ZONE_CONTROL_LEN': 'zonecontrol',
    'ZONE_COUNT_OFF': 'zonecontrol',
    'ZONE_HEAD_OFF': 'zonecontrol',
    'ZONE_HOME_BY_KIND': 'zoneentry',
    'ZONE_LIVE_WARZONES': 'zonecontrol',
    'ZONE_MAPNO': 'areachange',
    'ZONE_MAPNO_SPEC': 'areachange',
    'ZONE_ROWS_D83': 'zonecontrol',
    'ZONE_ROW_LEN': 'zonecontrol',
    'ZONE_ROW_MAX': 'zonecontrol',
    'ZONE_ROW_OFF': 'zonecontrol',
    '_BATTLE_END_ERR': 'battleend',
    '_BATTLE_ENEMIES_ERR': 'squad',
    '_BATTLE_OBJECTIVE_ERR': 'battleend',
    '_DEVTOOL_NOTE': 'wirelog',
    '_LAYOUT_ERR': 'npccast',
    '_OBJECTIVE_ERR': 'battleend',
    '_PERSON_NAMES': 'npccast',
    '_PUSH_PROBE_ERR': 'pushes',
    '_RFC1918_NETS': 'addressing',
    '_SW_LOADED': 'sectorwins',
    '_USN_STAFF': 'npccast',
    '_WAR_STATE': 'warstate',
    '_as_world_channel': 'worldchannel',
    '_bay_wanzer_parts': 'npcroster',
    '_bb': 'missionblock',
    '_bind_world_entry': 'worldchannel',
    '_bp': 'battlepop',
    '_cp932_field': 'pushes',
    '_credit_room_kill': 'referee',
    '_db_lock': 'charstore',
    '_db_ready': 'charstore',
    '_default_accounts_db': 'identity',
    '_default_store': 'charstore',
    '_econ_value': 'economy',
    '_env_float': 'knobs',
    '_env_int': 'knobs',
    '_epoch': 'squadron',
    '_event_term': 'scriptcall',
    '_f': 'poplook',
    '_gender_byte': 'poplook',
    '_group_entries': 'groupchannel',
    '_group_id_pair': 'squadron',
    '_i': 'squadron',
    '_identity_by_ip': 'identity',
    '_ids_env': 'room',
    '_ip_or_none': 'addressing',
    '_ipaddress': 'deps',
    '_is_battle_chan': 'rooms',
    '_is_rfc1918': 'addressing',
    '_iso_unix': 'servicerecord',
    '_k': 'defaults',
    '_lan_client_nets': 'addressing',
    '_look_field': 'poplook',
    '_ma': 'missionblock',
    '_mission_epoch': 'missionbook',
    '_mission_iso': 'missionbook',
    '_mn': 'popsweep',
    '_model_n': 'popsweep',
    '_msn_fields': 'community',
    '_name_at': 'charstore',
    '_next_token': 'charstore',
    '_note_battle_record': 'referee',
    '_now_unix': 'servicerecord',
    '_npc_pop_record': 'npcroster',
    '_npck': 'npcroster',
    '_npct': 'npcroster',
    '_parse_battle_dummy': 'battlepop',
    '_parse_battle_maps': 'battlemaps',
    '_parse_dummy_kill': 'battlepop',
    '_parse_look_fixed': 'poplook',
    '_parse_model': 'popsweep',
    '_parse_model_from_roster': 'popself',
    '_parse_pop': 'popsweep',
    '_parse_pop_npc': 'npccast',
    '_parse_referee': 'battlepop',
    '_parse_spec_keep_names': 'npccast',
    '_parse_status_flags': 'status',
    '_pop_n': 'popsweep',
    '_pos_n': 'popsweep',
    '_proven_by_ip': 'identity',
    '_ps2_id_set': 'zoneentry',
    '_relay_battle_record': 'referee',
    '_res_idx': 'resume',
    '_rest': 'popsweep',
    '_row_int_map': 'sectorwins',
    '_selftest_run': 'selftests',
    '_serial_n': 'shop',
    '_serve_datagram': 'datagram',
    '_sex': 'popself',
    '_sex_n': 'popself',
    '_status_sex': 'status',
    '_store_lock': 'identity',
    '_sw_ensure_loaded': 'sectorwins',
    '_sw_legacy': 'sectorwins',
    '_sw_write': 'sectorwins',
    '_sweep_n': 'zoneentry',
    '_token_account': 'charstore',
    '_u8_pair': 'missionblock',
    '_udp_ctx': 'worldchannel',
    '_udp_key_hint': 'room',
    '_udp_nokey_dumped': 'udpconfig',
    '_undestroy': 'popself',
    '_war_tick': 'warstate',
    '_within_cone': 'battlepop',
    '_world_entries': 'worldchannel',
    '_world_entries_lock': 'worldchannel',
    '_xz_dist': 'battlepop',
    'accepted_list_rows': 'missionbook',
    'accepted_missions': 'missionbook',
    'account_for': 'identity',
    'accounts_conn': 'identity',
    'account_for_token': 'charstore',
    'add_stored_item': 'inventory',
    'advance_progress': 'progress',
    'advance_sweep': 'zoneentry',
    'answered_0159': 'scriptcall',
    'apply_event_rule': 'scriptcall',
    'area_access': 'permits',
    'area_change_destinations': 'areachange',
    'area_change_mapno': 'areachange',
    'area_open_bitmap': 'permits',
    'area_pass_item': 'permits',
    'area_permit_cost': 'permits',
    'area_sector_state': 'areatargets',
    'area_target_taken': 'areatargets',
    'area_target_tiles': 'areatargets',
    'argparse': 'deps',
    'band_rosters': 'npcroster',
    'battle_area_box': 'missionblock',
    'battle_end_body': 'battleend',
    'battle_end_packet': 'battleend',
    'battle_end_trigger': 'referee',
    'battle_kills': 'battleend',
    'battle_pay': 'battleend',
    'battle_room_hostile': 'rooms',
    'battle_room_key': 'squad',
    'battle_room_killer': 'rooms',
    'battle_room_pop_args': 'rooms',
    'battle_side_for': 'popnation',
    'battle_squad_for': 'squad',
    'battle_state': 'referee',
    'bkey': 'referee',
    'build': 'packet',
    'ceasefire_bonus': 'servicerecord',
    'ceasefire_owed': 'servicerecord',
    'ceasefire_share': 'servicerecord',
    'chan_bkey': 'referee',
    'chan_where': 'worldchannel',
    'character_from_013e': 'charstore',
    'character_nation': 'popnation',
    'chat_echo_name': 'warmap',
    'checksum': 'packet',
    'city_rank': 'citytable',
    'city_rows': 'citytable',
    'city_table_payload': 'citytable',
    'city_table_push': 'citytable',
    'claim_group_entry': 'groupchannel',
    'claim_world_account': 'worldchannel',
    'class_exp_of': 'classes',
    'class_level': 'classes',
    'class_table_block': 'classes',
    'class_table_summary': 'classes',
    'contentauth': 'deps',
    'cosmetics_for': 'cosmetics',
    'datetime': 'deps',
    'derive_band_roster': 'npccast',
    'describe': 'packet',
    'describe_0159': 'scriptcall',
    'describe_move_req': 'move',
    'describe_script_choice': 'zoneentry',
    'devtool_ctx': 'devtool',
    'devtool_start': 'devtool',
    'endpoint': 'addressing',
    'endpoint_net': 'addressing',
    'enemy_missions_running': 'popnation',
    'enemy_side_for': 'popnation',
    'entry_place': 'move',
    'event_rule_for': 'scriptcall',
    'face_radians': 'npccast',
    'faction_mapkind': 'zoneentry',
    'fedevtool': 'deps',
    'fee_push_body': 'pushes',
    'fee_push_packet': 'pushes',
    'fire_relay': 'squad',
    'fit_records': 'udpconfig',
    'fmodb': 'deps',
    'fmodevtool': 'deps',
    'fmolayout': 'deps',
    'fmomsn': 'deps',
    'fmosectors': 'deps',
    'fmostore': 'deps',
    'fmowar': 'deps',
    'fmoworld': 'deps',
    'from_wire': 'charlist',
    'group_attach_body': 'grouplogin',
    'group_attach_packet': 'grouplogin',
    'group_blob_update': 'groupchannel',
    'group_board_rows': 'community',
    'group_ended_body': 'pushes',
    'group_entry': 'grouplogin',
    'group_join': 'groupchannel',
    'group_leader_for': 'groupchannel',
    'group_login_notify_body': 'pushes',
    'group_member_flags': 'groupchannel',
    'group_member_row': 'groupchannel',
    'group_player_rows': 'groupchannel',
    'group_push_flags': 'groupchannel',
    'group_queue': 'groupchannel',
    'group_remote_member_record': 'groupchannel',
    'hangar_bays': 'hangar',
    'hangar_owner_password': 'hangar',
    'hangar_place': 'hangar',
    'hangar_request': 'hangar',
    'hangar_resident_units': 'hangar',
    'has_named_character': 'charlist',
    'hexdump': 'wirelog',
    'hitlist_echo': 'squad',
    'hitlist_for_viewer': 'squad',
    'host_for': 'addressing',
    'hud_banner': 'referee',
    'id_for_viewer': 'squad',
    'in_mapkind_band': 'zoneentry',
    'insignia_for': 'squadron',
    'insignia_payload': 'squadron',
    'insignia_push': 'squadron',
    'inventory_from_setups': 'inventory',
    'ipv4_le': 'addressing',
    'is_person_name': 'npccast',
    'item_announce_body': 'pushes',
    'item_mint_payload': 'shop',
    'item_record': 'inventory',
    'json': 'deps',
    'layout_band': 'npcroster',
    'list_entry': 'charlist',
    'list_payload': 'charlist',
    'load_class_curve': 'classes',
    'load_cosmetics': 'cosmetics',
    'load_event_table': 'scriptcall',
    'load_insignia': 'squadron',
    'load_missions': 'progress',
    'load_rank_ladder': 'ranks',
    'load_roster': 'charstore',
    'lobapi_payload': 'lobapi',
    'lobby_cast_paused': 'squad',
    'lobby_message_body': 'lobbymessage',
    'lobby_message_packet': 'lobbymessage',
    'lobby_push_packet': 'pushes',
    'log': 'wirelog',
    'mark_body': 'lobapi',
    'math': 'deps',
    'member_check_names': 'popnames',
    'member_for_ip': 'identity',
    'merge_inventory': 'inventory',
    'mint_serial': 'shop',
    'mint_token': 'charstore',
    'mission_accept_verdict': 'missionbook',
    'mission_already_accepted': 'missionbook',
    'mission_area_fields': 'missionblock',
    'mission_battle_apply': 'missionbook',
    'mission_cancel_apply': 'missionbook',
    'mission_deadline': 'missionbook',
    'mission_fields': 'missionblock',
    'mission_find': 'missionbook',
    'mission_for_byte': 'scriptcall',
    'mission_key': 'missionbook',
    'mission_leader_id': 'missionblock',
    'mission_list_fields': 'missionlist',
    'mission_list_rows': 'missionlist',
    'mission_list_why': 'missionlist',
    'mission_next_key': 'missionbook',
    'mission_pay_rows': 'missionbook',
    'mission_prune': 'missionbook',
    'mission_record_fill': 'missionlist',
    'mission_refusal_text': 'missionboard',
    'mission_report_apply': 'missionbook',
    'mission_report_text': 'missionbook',
    'mission_requirements': 'missionbook',
    'mission_row_fields': 'missionbook',
    'mission_status': 'missionbook',
    'move_kind_for': 'move',
    'move_list_for': 'move',
    'move_state_len': 'squad',
    'msn_reply': 'community',
    'msn_row_spec': 'community',
    'msn_row_table': 'community',
    'msn_rows': 'community',
    'name_clash': 'charstore',
    'nation_for_session': 'zoneentry',
    'next_client_script': 'zoneentry',
    'next_free_id': 'charstore',
    'next_mapkind': 'zoneentry',
    'next_mapno': 'zoneentry',
    'next_payday_unix': 'servicerecord',
    'next_pilotpos': 'zoneentry',
    'next_pop_model': 'popsweep',
    'next_pop_pos': 'popsweep',
    'next_pop_sex': 'popself',
    'next_pop_type': 'popsweep',
    'npc_cast_configured': 'npcroster',
    'npc_move_queue': 'npcroster',
    'npc_moves': 'npcroster',
    'objective_tick': 'referee',
    'objective_zone_contains': 'referee',
    'online_players': 'popnames',
    'os': 'deps',
    'owned_by': 'roomrelay',
    'parse': 'packet',
    'parse_0139': 'sortie',
    'parse_0159': 'scriptcall',
    'parse_01ac': 'squadron',
    'parse_account_pin': 'identity',
    'parse_battle_end': 'battleend',
    'parse_battle_enemies': 'squad',
    'parse_battle_objective': 'battleend',
    'parse_city_table': 'citytable',
    'parse_credentials': 'packet',
    'parse_exp_rows': 'battleend',
    'parse_hangar_pw': 'move',
    'parse_hitlist': 'squad',
    'parse_insignia_set': 'squadron',
    'parse_item_request': 'shop',
    'parse_lobapi_mark': 'lobapi',
    'parse_move_list': 'move',
    'parse_objective': 'battleend',
    'parse_parts_stock': 'partsstock',
    'parse_permit_ranks': 'permits',
    'parse_place_id': 'move',
    'parse_push_probe': 'pushes',
    'parse_review_caps': 'servicerecord',
    'parse_room_maps': 'move',
    'parse_setup_parts': 'inventory',
    'parse_war_fields': 'warstate',
    'parse_zone_control': 'zonecontrol',
    'parse_zone_mapno': 'areachange',
    'parts_stock_block': 'partsstock',
    'parts_stock_payload': 'partsstock',
    'parts_stock_push': 'partsstock',
    'paybook_fill': 'servicerecord',
    'paybook_rows': 'servicerecord',
    'paydays_owed': 'servicerecord',
    'peer_link_pop_args': 'peerlink',
    'peer_link_serve': 'peerlink',
    'peer_stream_for': 'peerlink',
    'permit_rank_passes': 'permits',
    'pilot_death_trigger': 'referee',
    'place_id': 'move',
    'place_map': 'move',
    'place_name': 'move',
    'place_population': 'move',
    'place_rows': 'move',
    'playtime_dhm': 'move',
    'pop_client_kind_for': 'popself',
    'pop_look_for': 'poplook',
    'pop_model_for': 'popself',
    'pop_names_for': 'popnames',
    'pop_nation_for': 'popnation',
    'pop_parts_for': 'popparts',
    'pop_sex_for': 'popnames',
    'progress_done': 'progress',
    'progress_frontier': 'progress',
    'queue_group_entry': 'groupchannel',
    'queue_world_entry': 'worldchannel',
    'rank_for_contribution': 'ranks',
    'rank_name': 'ranks',
    'rank_pay': 'ranks',
    'rank_threshold': 'ranks',
    're': 'deps',
    'rebind_on_restart': 'worldchannel',
    'referee_shot': 'referee',
    'remember_identity': 'identity',
    'remove_stored_item': 'inventory',
    'reply_0133': 'inventory',
    'reply_013a': 'sortie',
    'reply_014a': 'status',
    'reply_014e': 'sortiepush',
    'reply_0153': 'zoneentry',
    'reply_0155': 'grouplogin',
    'reply_0163': 'groupchannel',
    'reply_0166': 'inventory',
    'reply_016f': 'move',
    'reply_0183': 'move',
    'reply_018e': 'missionlist',
    'reply_018e_short': 'missionlist',
    'reply_018f': 'missionlist',
    'reply_019d': 'charselect',
    'reply_01a3': 'cosmetics',
    'reply_01a9': 'areatargets',
    'reply_01ad': 'squadron',
    'reply_01c1': 'missionblock',
    'reply_01f5': 'battlemaps',
    'reply_warmap_list': 'warmap',
    'reset_world_channel': 'rooms',
    'resolve_place_pick': 'move',
    'result_push_body': 'resultpush',
    'result_push_packet': 'resultpush',
    'resume_resource_path': 'resume',
    'resupply_body': 'pushes',
    'review_demoted_contribution': 'servicerecord',
    'review_successes': 'servicerecord',
    'review_verdict': 'servicerecord',
    'room_flush': 'roomrelay',
    'room_left': 'rooms',
    'room_mates': 'rooms',
    'room_prune': 'rooms',
    'room_queue': 'roomrelay',
    'roster_for': 'npcroster',
    'roster_payload': 'charlist',
    'run': 'main',
    'save_roster': 'charstore',
    'scene_reply_hid': 'udpconfig',
    'script_id_for': 'zoneentry',
    'script_nation': 'zoneentry',
    'se_marked': 'npccast',
    'seal': 'packet',
    'sector_win_record': 'sectorwins',
    'sector_wins_between': 'sectorwins',
    'sector_wins_load': 'sectorwins',
    'sector_wins_save': 'sectorwins',
    'seed_new_character': 'economy',
    'seed_summary': 'economy',
    'selftest': 'selftests',
    'serial_equipped': 'trade',
    'serve_client': 'tcpserver',
    'serve_mission_client': 'community',
    'serve_udp': 'worldchannel',
    'service_record_block': 'servicerecord',
    'session_key': 'packet',
    'settle_world_entry': 'worldchannel',
    'setup_block': 'zoneentry',
    'setup_entry': 'inventory',
    'setup_parts_for': 'inventory',
    'setups_in_use': 'hangar',
    'socket': 'deps',
    'sortie_fields': 'sortie',
    'sortie_mapno': 'sortie',
    'sortie_push_armed': 'sortiepush',
    'sortie_push_fields': 'sortiepush',
    'sortie_push_mapno': 'sortiepush',
    'sortie_push_packet': 'sortiepush',
    'squad_batch_filter': 'squad',
    'squad_credit_kill': 'squad',
    'squad_gap': 'squad',
    'squad_note_hits': 'squad',
    'squad_owner_uid': 'squad',
    'squad_positions': 'squad',
    'squad_relay': 'squad',
    'squadron_activate_body': 'squadron',
    'squadron_insignia_push_body': 'squadron',
    'squadron_insignia_word': 'squadron',
    'squadron_row_body': 'squadron',
    'starter_setup': 'inventory',
    'status_block_pristine': 'selftests',
    'status_block_zero_or_knobbed': 'selftests',
    'status_body': 'status',
    'status_fields': 'status',
    'status_mark_body': 'status',
    'store_accounts': 'identity',
    'stored_item_records': 'inventory',
    'stored_items': 'inventory',
    'stored_setup1_parts': 'popparts',
    'struct': 'deps',
    'sys': 'deps',
    'threading': 'deps',
    'time': 'deps',
    'time_sync_body': 'timesync',
    'time_sync_packet': 'timesync',
    'to_wire': 'charlist',
    'trade_apply': 'trade',
    'trade_block_key': 'trade',
    'trade_block_money': 'trade',
    'trade_block_slots': 'trade',
    'trade_for': 'trade',
    'trade_host_of_alias': 'trade',
    'trade_open': 'trade',
    'trade_partner': 'trade',
    'trade_push_record': 'trade',
    'trade_release': 'trade',
    'trade_state_record': 'trade',
    'trade_validate': 'trade',
    'trained': 'classes',
    'trial_key': 'packet',
    'use_db': 'charstore',
    'usn_counterpart': 'npccast',
    'usn_roster': 'npccast',
    'wallet_money': 'economy',
    'war_sector_records': 'warstate',
    'war_state': 'warstate',
    'warmap_census': 'warmap',
    'warmap_entry_fill': 'warmap',
    'warmap_rows': 'warmap',
    'warmap_sector_for': 'warmap',
    'warmap_selector': 'warmap',
    'with_free_slot': 'charlist',
    'zone_control_nation_warning': 'zonecontrol',
    'zone_control_payload': 'zonecontrol',
    'zone_control_push': 'zonecontrol',
    'zone_mapno': 'areachange',
    'zone_of': 'rooms',
}
_MODULES = {m: importlib.import_module("fmoserver." + m) for m in (
    'deps',
    'defaults',
    'knobs',
    'wirelog',
    'packet',
    'handshake',
    'addressing',
    'msgnames',
    'charlist',
    'charstore',
    'identity',
    'charselect',
    'resume',
    'status',
    'classes',
    'ranks',
    'economy',
    'servicerecord',
    'progress',
    'zoneentry',
    'move',
    'hangar',
    'areachange',
    'zonecontrol',
    'citytable',
    'partsstock',
    'inventory',
    'shop',
    'permits',
    'cosmetics',
    'squadron',
    'lobapi',
    'missionblock',
    'missionlist',
    'missionboard',
    'missionbook',
    'sectorwins',
    'areatargets',
    'warmap',
    'warstate',
    'sortie',
    'sortiepush',
    'battlemaps',
    'battlegroups',
    'grouplogin',
    'withdraw',
    'scriptcall',
    'resultpush',
    'battleend',
    'lobbymessage',
    'timesync',
    'pushes',
    'trade',
    'coliseum',
    'pilotrecord',
    'settlement',
    'session',
    'tcpserver',
    'community',
    'udpconfig',
    'popself',
    'popnames',
    'poplook',
    'popnation',
    'popparts',
    'popsweep',
    'battlepop',
    'roomcast',
    'npccast',
    'npcroster',
    'room',
    'worldchannel',
    'groupchannel',
    'missiongroups',
    'rooms',
    'squad',
    'roomrelay',
    'peerlink',
    'referee',
    'datagram',
    'devtool',
    'gatetool',
    'loot',
    'penalty',
    'solo',
    'defection',
    'main',
    'selftests',
)}


class _Facade(types.ModuleType):
    """`fmo.<name>` reads and writes go to the owning fmoserver module."""

    def __getattr__(self, name):
        mod = _OWNERS.get(name)
        if mod is None:
            raise AttributeError(f"module 'fmo' has no attribute {name!r}")
        return getattr(_MODULES[mod], name)

    def __setattr__(self, name, value):
        mod = _OWNERS.get(name)
        if mod is None:
            super().__setattr__(name, value)
            return
        setattr(_MODULES[mod], name, value)
        # a name imported by name (fmostore from deps, log from wirelog) is a
        # copy in every module that imported it; a patch has to reach each copy
        for other in _MODULES.values():
            if other is not _MODULES[mod] and name in vars(other):
                setattr(other, name, value)

    def __delattr__(self, name):
        mod = _OWNERS.get(name)
        if mod is None:
            super().__delattr__(name)
            return
        delattr(_MODULES[mod], name)

    def __dir__(self):
        return sorted(set(super().__dir__()) | set(_OWNERS))


class _FlatGlobals(dict):
    """`globals()` of the old single file, as the moved code still uses it."""

    def __init__(self, facade):
        super().__init__()
        self._facade = facade

    def __getitem__(self, name):
        try:
            return getattr(self._facade, name)
        except AttributeError:
            raise KeyError(name) from None

    def __setitem__(self, name, value):
        setattr(self._facade, name, value)

    def __delitem__(self, name):
        try:
            delattr(self._facade, name)
        except AttributeError:
            raise KeyError(name) from None

    def __contains__(self, name):
        return name in _OWNERS or name in vars(self._facade)

    def get(self, name, default=None):
        try:
            return self[name]
        except KeyError:
            return default

    def setdefault(self, name, default=None):
        if name not in self:
            self[name] = default
        return self[name]

    def pop(self, name, *default):
        try:
            value = self[name]
        except KeyError:
            if default:
                return default[0]
            raise
        del self[name]
        return value

    def update(self, *args, **kw):
        for k, v in dict(*args, **kw).items():
            self[k] = v

    def keys(self):
        return list(_OWNERS)

    def __iter__(self):
        return iter(_OWNERS)

    def __len__(self):
        return len(_OWNERS)


sys.modules[__name__].__class__ = _Facade
FLAT_GLOBALS = _FlatGlobals(sys.modules[__name__])


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--selftest", action="store_true")
    args = ap.parse_args()
    sys.exit(_MODULES['selftests'].selftest() if args.selftest else _MODULES['main'].run())
